server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer
          uri: http://localhost:8001
          predicates:
            - Path=/customer/**
        - id: product
          uri: http://localhost:8002
          predicates:
            - Path=/product/**
        - id: account
          uri: http://localhost:8003
          predicates:
            - Path=/account/**
        - id: transaction
          uri: http://localhost:8004
          predicates:
            - Path=/transaction/**